#!/usr/bin/env perl
use strict;

my $hash1 = 'e8895ab6cd04db94b1d0a82a8fe62b7f';
my $hash200 = '6395166d71721b6ef0ee36f014d72a5d';
my $hash10000 = 'bf7625d8c5982c0b7582e1a240086603';

print "Share target size 1:      ";
my $hash = `../pricer.py 1 < test.in | md5`;
if ($hash == $hash1) {
        print "PASS\n";
} else {
        print "FAIL\n";
}

print "Share target size 200:    ";
my $hash = `../pricer.py 200 < test.in | md5`;
if ($hash == $hash200) {
        print "PASS\n";
} else {
        print "FAIL\n";
}

print "Share target size 10000:  ";
my $hash = `../pricer.py 10000 < test.in | md5`;
if ($hash == $hash10000) {
        print "PASS\n";
} else {
        print "FAIL\n";
}

print "Stdout error test:\n";
my $corrupt_log = `../pricer.py 10000 < test.corrupt.in`;
